name: version

on:
  issues:
    types: [opened]

jobs:
  version_and_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification on Package Update
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{
          "message": "A new issue has been raised in flutter deriv packages."
        }' \
          "https://hooks.slack.com/triggers/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"
      shell: bash