name: issue_created

on:
  issues:
    types: [opened]

env:
  issue_title: ${{ github.event.issue.title }}

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup jq
        run: sudo apt-get install jq

      - name: Send Slack Notification on Github Issue Opened
        env:
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/triggers/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"
        run: |
          LABELS=$(echo '${{ toJson(github.event.issue.labels.*.name) }}' | jq -r 'join(", ")')
          curl -X POST -H 'Authorization: Bearer xoxb-13075252481-6367737895764-TwByh2DBvKC7oLZxy0Q5g3ib' \
              -H 'Content-type: application/json' \
              --data "{
                \"channel\": \"test_bassam\",
                \"text\": \"Issue Created\",
                \"blocks\": [
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"<!channel> *New Github Issue*\"
                    }
                  },
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"*Issue Creator:* ${{ github.event.issue.user.login }}\n*Issue Title:* $issue_title\n*Issue URL:* ${{ github.event.issue.html_url }}\n*Issue Labels:* $LABELS\"
                    }
                  }
                ]
              }" \
              https://slack.com/api/chat.postMessage
        shell: bash