name: issue_created

on:
  issues:
    types: [opened]

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup jq
        run: sudo apt-get install jq

      - name: Send Slack Notification on Github Issue Opened
        env:
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/triggers/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"
        run: |
          LABELS=$(echo $LABELS_JSON | jq -r 'join(", ")')
          curl -X POST -H 'Content-type: application/json' \
          --data '{
          "issue_creator": "${{ github.event.issue.user.login }}",
          "issue_title": "${{ github.event.issue.title }}",
          "issue_url": "${{ github.event.issue.html_url }}",
          "issue_labels": "${{ $LABELS }}"
          }' \
            "https://hooks.slack.com/triggers/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"
        shell: bash
