name: issue_created

on:
  issues:
    types: [opened]

jobs:
  version_and_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup jq
        run: sudo apt-get install jq

      - name: Send Slack Notification on Package Update
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_LABELS: ${{ toJson(github.event.issue.labels.*.name) }}
          ISSUE_CREATOR: ${{ github.event.issue.user.login }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/triggers/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"
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
          "issue_creator": ${{ ISSUE_CREATOR }},
          "issue_title": ${{ ISSUE_TITLE }},
          "issue_url": ${{ ISSUE_URL }},
          "issue_labels": ${{ ISSUE_LABEL }}"
          }' \
            "https://hooks.slack.com/triggers/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"
        shell: bash
